#!/bin/sh -e

#
# Copyright 2015-2016 Preetam J. D'Souza
# Copyright 2016 The Maru OS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Maru Linux initialization.
#
# This may be run before the entire system is up and running,
# (e.g. cross-bootstrap image build) so don't rely on any commands
# like systemctl.
#
# This needs to be idempotent.
#
# Creating a user that already exists returns failure so we use
# "id" to check if the user exists first.
#
# We ignore group creation failures ("|| true") since the subsequent
# adduser <user> <group> will fail if the group does not exist.
#

USER="maru"

# create default user account
if ! id -u "$USER" ; then
    adduser --disabled-password --gecos "" "$USER"
    # default password is username
    echo "${USER}:${USER}" | chpasswd
fi

# sudo rights
adduser "$USER" sudo

# internet access
addgroup --gid 3003 inet || true
adduser "$USER" inet

# raw sockets (ping)
addgroup --gid 3004 inet_raw || true
adduser "$USER" inet_raw

# sdcard read permissions
addgroup --gid 1028 sdcard_r || true
adduser "$USER" sdcard_r

## systemd ##

# This is harmless as everything still works with this enabled,
# but only Android should do network interface configuration.
# systemd networking.service (ifup/ifdown) syncs with sysvinit
# so disable it using update-rc.d
/usr/sbin/update-rc.d networking disable

# disable sshd services by default
# systemd syncs with sysvinit so use update-rc.d too
/usr/sbin/update-rc.d ssh disable
if [ -e /etc/systemd/system/sshd.service ] ; then
    rm /etc/systemd/system/sshd.service
fi

# start mclient service on startup
ln -s /lib/systemd/system/mclient.service /etc/systemd/system/multi-user.target.wants/mclient.service

## udev ##

# remove any persistent interface naming rules
# This can be created when building Maru Desktop before
# our override kicks in.
PERSISTENT_NET_RULES="/etc/udev/rules.d/70-persistent-net.rules"
if [ -f "$PERSISTENT_NET_RULES" ] ; then
    rm "$PERSISTENT_NET_RULES"
fi

### LightDM configuration ###

if [ -e /etc/lightdm/lightdm.conf ] ; then
    mv /etc/lightdm/lightdm.conf /etc/lightdm/lightdm.conf.backup

    cat > /etc/lightdm/lightdm.conf <<EOF
[SeatDefaults]
autologin-user=$USER
EOF
fi

### XFCE tweaks ###

# make sure $USER owns everything
chown -R "$USER":"$USER" /var/maru

# sync home directory config and settings (trailing slash is important!)
rsync -a /var/maru/ "/home/$USER"

# remove Audio Mixer app
if [ -e /usr/share/applications/xfce4-mixer.desktop ] ; then
    echo "Hidden=true" >> /usr/share/applications/xfce4-mixer.desktop
fi

# remove Log Out app
if [ -e /usr/share/applications/xfce4-session-logout.desktop ] ; then
    echo "Hidden=true" >> /usr/share/applications/xfce4-session-logout.desktop
fi

# custom applications panel
# note: we are forced to overrride the default menu because desktop
# left-click applications menu cannot use a custom menu file
if [ -e  /etc/xdg/menus/xfce-applications.menu ] ; then
    mv /etc/xdg/menus/xfce-applications.menu /etc/xdg/menus/xfce-applications.menu.backup
fi
mv /etc/xdg/menus/maru-applications.menu /etc/xdg/menus/xfce-applications.menu

### Iceweasel configuration ###

if [ -e /etc/iceweasel/pref/iceweasel.js ] ; then
    cp /etc/iceweasel/pref/iceweasel.js /etc/iceweasel/pref/iceweasel.js.backup

    cat >> /etc/iceweasel/pref/iceweasel.js <<EOF

// Force desktop versions of websites by hiding armv7l
pref("general.useragent.override", "Mozilla/5.0 (X11; Linux; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.2.1");
EOF
fi

#DEBHELPER#

exit 0
