#!/bin/sh -e
#
# Maru Linux initialization.
#
# Error handling
# --------------
#
# This needs to be idempotent.
#
# Creating a user that already exists returns failure so we use
# "id" to check if the user exists first.
#
# We ignore group creation failures ("|| true") since the subsequent
# adduser <user> <group> will fail if the group does not exist.
#

USER="maru"
HOSTNAME="jessie"

# make sure the hostname is set correctly
hostnamectl set-hostname "$HOSTNAME"

# create default user account
id -u "$USER" || adduser "$USER"

# sudo rights
adduser "$USER" sudo

# internet access
addgroup --gid 3003 inet || true
adduser "$USER" inet

# raw sockets (ping)
addgroup --gid 3004 inet_raw || true
adduser "$USER" inet_raw

# sdcard read permissions (TODO add root?)
addgroup --gid 1028 sdcard_r || true
adduser "$USER" sdcard_r

## systemd ##

# disable networking services (ifup/ifdown)
# This is harmless as everything still works with this enabled,
# but only Android should do network interface configuration.
systemctl stop networking
systemctl daemon-reload
systemctl disable networking

# disable sshd services
systemctl stop ssh
systemctl disable ssh

# start mclient service on startup
systemctl enable mclient

## udev ##

# remove any persistent interface naming rules
# This can be created when building Maru Desktop before
# our override kicks in.
PERSISTENT_NET_RULES="/etc/udev/rules.d/70-persistent-net.rules"
if [ -f "$PERSISTENT_NET_RULES" ] ; then
    rm "$PERSISTENT_NET_RULES"
fi

### LightDM configuration ###

mv /etc/lightdm/lightdm.conf /etc/lightdm/lightdm.conf.backup

cat > /etc/lightdm/lightdm.conf <<EOF
[SeatDefaults]
autologin-user=$USER
EOF

### XFCE tweaks ###

# make sure $USER owns everything
chown -R "$USER":"$USER" /var/maru

# sync home directory config and settings (trailing slash is important!)
rsync -a /var/maru/ "/home/$USER"

# remove Audio Mixer app
echo "Hidden=true" >> /usr/share/applications/xfce4-mixer.desktop

# remove Log Out app
echo "Hidden=true" >> /usr/share/applications/xfce4-session-logout.desktop

# custom applications panel
# note: we are forced to overrride the default menu because desktop
# left-click applications menu cannot use a custom menu file
mv /etc/xdg/menus/xfce-applications.menu /etc/xdg/menus/xfce-applications.menu.backup
mv /etc/xdg/menus/maru-applications.menu /etc/xdg/menus/xfce-applications.menu

### Iceweasel configuration ###

cp /etc/iceweasel/pref/iceweasel.js /etc/iceweasel/pref/iceweasel.js.backup

cat >> /etc/iceweasel/pref/iceweasel.js <<EOF

// Force desktop versions of websites by hiding armv7l
pref("general.useragent.override", "Mozilla/5.0 (X11; Linux; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.2.1");
EOF

#DEBHELPER#

exit 0
