#!/bin/bash -e
#
# Any early initialization before package is installed.
#

# add jessie-backports before installing so dkpg can find all the dependencies
echo "deb http://http.debian.net/debian jessie-backports main" > /etc/apt/sources.list.d/backports.list
